resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: boss-deployer-repo
  type: git
  source:
    uri: git@github.com:smarla/boss-deployer.git
    branch: master
    private_key: {{concourse-private-ssh-key}}

jobs:
- name: versions
  plan:
    - do:

- name: provision
  plan:
    - do:

- name: configure
  plan:
    - do:

- name: spec
  plan:
    - do:

- name: balance
  plan:
    - do:

- name: shutdown
  plan:
    - do: